# Variable 'system.Debug' was defined in the Variables tab
trigger:
  branches:
    include:
    - main
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: auth-micro-frontend
      verbose: false
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: auth-micro-backend
      verbose: false
  - task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@7
    displayName: Prepare analysis on SonarQube Server
    inputs:
      SonarQube: 9566e120-0d17-47d4-82e9-074f904af399
      scannerMode: cli
      configMode: manual
      cliProjectKey: COMP367-Group5_COMP367-Group5_AZODG3CAJiP_amtEclN-
      projectKey: COMP367-Group5_COMP367-Group5_AZODG3CAJiP_amtEclN-
      cliSources: auth-micro-backend
      extraProperties: "# Additional properties that will be passed to the scanner, \n# Put one key=value per line, example:\n# sonar.exclusions=**/*.bin,node_modules/**, coverage/**\nsonar.javascript.lcov.reportPaths=coverage/lcov.info\n\n"
  - task: Npm@1
    displayName: npm run build
    inputs:
      command: custom
      workingDir: auth-micro-frontend
      verbose: false
      customCommand: run build
  - task: Npm@1
    displayName: npm test
    inputs:
      command: custom
      workingDir: auth-micro-backend
      verbose: false
      customCommand: test -- --coverage
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: >-
        set Build.SourceBranchName=

        set Build.SourceBranch=
  - task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@7
    displayName: Run Code Analysis
  - task: SonarSource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@7
    displayName: Publish Quality Gate Result
  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: drop'
    inputs:
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
